name: Jekyll site CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' 
        bundler-cache: true
    - name: Build and test
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        bundle exec jekyll build --trace